import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_KEY = 'app_language';

// English translations
const en: Record<string, string> = {
  // Common
  'common.loading': 'Loading...',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.done': 'Done',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.refresh': 'Refresh',
  'common.close': 'Close',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.or': 'or',
  'common.and': 'and',

  // Navigation
  'nav.home': 'Home',
  'nav.requests': 'Requests',
  'nav.profile': 'Profile',
  'nav.history': 'History',
  'nav.settings': 'Settings',

  // Auth
  'auth.login': 'Login',
  'auth.logout': 'Logout',
  'auth.signup': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.resetPassword': 'Reset Password',
  'auth.phoneNumber': 'Phone Number',
  'auth.sendOTP': 'Send OTP',
  'auth.verifyOTP': 'Verify OTP',
  'auth.signInWithGoogle': 'Sign in with Google',
  'auth.signInWithPhone': 'Sign in with Phone',
  'auth.noAccount': "Don't have an account?",
  'auth.hasAccount': 'Already have an account?',
  'auth.logoutConfirm': 'Are you sure you want to logout?',
  'auth.logoutDescription': 'You will need to login again to access your account.',

  // Profile
  'profile.title': 'Profile',
  'profile.editProfile': 'Edit Profile',
  'profile.fullName': 'Full Name',
  'profile.phoneNumber': 'Phone Number',
  'profile.bloodGroup': 'Blood Group',
  'profile.area': 'Area',
  'profile.email': 'Email',
  'profile.memberSince': 'Member Since',
  'profile.updateSuccess': 'Profile updated successfully!',
  'profile.updateError': 'Failed to update profile',

  // Donor
  'donor.title': 'Donor Settings',
  'donor.description': 'Manage your blood donation availability',
  'donor.registerAsDonor': 'Register as Donor',
  'donor.receiveRequests': 'Receive blood donation requests',
  'donor.availableToDonate': 'Available to Donate',
  'donor.toggleAvailability': 'Toggle your availability',
  'donor.inCooldown': 'In cooldown period',
  'donor.cooldownInfo': 'Cooldown Information',
  'donor.cooldownDays': 'days remaining',
  'donor.cooldownEnds': 'Cooldown ends',
  'donor.lastDonation': 'Last Donation',
  'donor.neverDonated': 'Never donated',
  'donor.moreThan3Months': 'More than 3 months ago',
  'donor.lessThan3Months': 'Less than 3 months ago',
  'donor.firstDonation': 'This will be my first donation',
  'donor.readyToDonate': 'Ready to donate again',
  'donor.willBeInCooldown': "You'll be in cooldown period",
  'donor.daysAgo': 'How many days ago?',
  'donor.immediatelyAvailable': "You'll be immediately available for donation",
  'donor.registerSuccess': 'You are now registered as a donor!',
  'donor.modeDisabled': 'Donor mode disabled',
  'donor.status.available': 'Available',
  'donor.status.unavailable': 'Unavailable',
  'donor.status.cooldown': 'Cooldown',

  // Requests
  'requests.title': 'Blood Requests',
  'requests.incoming': 'Incoming',
  'requests.myRequests': 'My Requests',
  'requests.scheduled': 'Scheduled',
  'requests.createRequest': 'Create Request',
  'requests.patientName': 'Patient Name',
  'requests.hospital': 'Hospital',
  'requests.bagsNeeded': 'Bags Needed',
  'requests.urgency': 'Urgency',
  'requests.notes': 'Notes',
  'requests.contactNumber': 'Contact Number',
  'requests.noRequests': 'No requests found',
  'requests.accept': 'Accept',
  'requests.decline': 'Decline',
  'requests.cancel': 'Cancel Request',
  'requests.complete': 'Mark Complete',
  'requests.viewHistory': 'View History',
  'requests.status.pending': 'Pending',
  'requests.status.accepted': 'Accepted',
  'requests.status.declined': 'Declined',
  'requests.status.completed': 'Completed',
  'requests.status.cancelled': 'Cancelled',
  'requests.status.expired': 'Expired',
  'requests.urgency.normal': 'Normal',
  'requests.urgency.urgent': 'Urgent',
  'requests.urgency.critical': 'Critical',

  // History
  'history.title': 'History',
  'history.myDonations': 'My Donations',
  'history.myRequests': 'My Requests',
  'history.totalDonations': 'Total Donations',
  'history.bagsDonated': 'Bags Donated',
  'history.peopleHelped': 'People Helped',
  'history.totalRequests': 'Total Requests',
  'history.completed': 'Completed',
  'history.pending': 'Pending',
  'history.noHistory': 'No history found',
  'history.filterAll': 'All',
  'history.filterCompleted': 'Completed',
  'history.filterPending': 'Pending',
  'history.filterAccepted': 'Accepted',
  'history.filterDeclined': 'Declined',
  'history.filterCancelled': 'Cancelled',
  'history.filterExpired': 'Expired',

  // Home
  'home.welcome': 'Welcome',
  'home.findDonors': 'Find Donors',
  'home.requestBlood': 'Request Blood',
  'home.becomeDonor': 'Become a Donor',
  'home.nearbyDonors': 'Nearby Donors',
  'home.recentRequests': 'Recent Requests',
  'home.quickActions': 'Quick Actions',

  // Notifications
  'notifications.title': 'Notifications',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.noNotifications': 'No notifications',
  'notifications.enable': 'Enable Notifications',
  'notifications.enabled': 'Push notifications enabled',
  'notifications.enableDescription': 'Get notified when someone needs blood',

  // Settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.languageDescription': 'Choose your preferred language',
  'settings.english': 'English',
  'settings.bangla': 'বাংলা',
  'settings.notifications': 'Notifications',
  'settings.privacy': 'Privacy',
  'settings.about': 'About',
  'settings.help': 'Help & Support',

  // Location
  'location.title': 'Location',
  'location.enable': 'Enable Location',
  'location.enableDescription': 'Allow location access to find nearby donors',
  'location.sharing': 'Location Sharing',
  'location.sharingActive': 'Sharing your location',
  'location.allowAccess': 'Allow Location Access',
  'location.skipForNow': 'Skip for now',

  // Errors
  'error.general': 'Something went wrong',
  'error.network': 'Network error. Please try again.',
  'error.notFound': 'Page not found',
  'error.unauthorized': 'Please login to continue',

  // Login page specific
  'login.title': 'RoktoLagbe',
  'login.subtitle': 'Emergency blood donation coordination in Bangladesh',
  'login.feature1.title': 'Find Donors Instantly',
  'login.feature1.description': 'Search by blood group and area',
  'login.feature2.title': 'Emergency Alerts',
  'login.feature2.description': 'Send urgent requests to matching donors',
  'login.feature3.title': 'Navigate to Hospital',
  'login.feature3.description': 'Get directions to the patient location',
  'login.google': 'Google',
  'login.phone': 'Phone',
  'login.email': 'Email',
  'login.tagline': 'Every drop counts',

  // Auth additional
  'auth.continueWithGoogle': 'Continue with Google',
  'auth.signingIn': 'Signing in...',
  'auth.sendingOTP': 'Sending OTP...',
  'auth.verifying': 'Verifying...',
  'auth.verifyAndSignIn': 'Verify & Sign In',
  'auth.changeNumber': 'Change Number',
  'auth.enterOTP': 'Enter OTP',
  'auth.otpSentTo': '6-digit code sent to',
  'auth.enterBDPhone': 'Enter your Bangladesh phone number',
  'auth.creating': 'Creating...',
  'auth.sending': 'Sending...',
  'auth.createAccount': 'Create Account',
  'auth.sendResetLink': 'Send Reset Link',
  'auth.signIn': 'Sign In',
  'auth.resetEmailInfo': 'Enter your email and we will send you a password reset link.',
  'auth.passwordHint.signup': 'Must be at least 6 characters.',
  'auth.passwordHint.signin': 'The password you used when signing up.',

  // Create Request page
  'createRequest.title': 'Create Blood Request',
  'createRequest.formTitle': 'Blood Request Form',
  'createRequest.formDescription': 'Fill in the details to find blood donors',
  'createRequest.requestFrom': 'Request from',
  'createRequest.fillDetails': 'Fill in the details to request from this donor',
  'createRequest.requestType': 'Request Type',
  'createRequest.immediate': 'Immediate',
  'createRequest.bookForLater': 'Book for Later',
  'createRequest.bookingInfo': 'Schedule blood donation for a future date (e.g., surgery, pregnancy)',
  'createRequest.date': 'Date',
  'createRequest.time': 'Time',
  'createRequest.requestForSelf': 'Request for Myself',
  'createRequest.autoFill': 'Your details will be auto-filled',
  'createRequest.patientName': 'Patient Name',
  'createRequest.contactPhone': 'Contact Phone',
  'createRequest.bloodGroup': 'Blood Group',
  'createRequest.selectBloodGroup': 'Select blood group',
  'createRequest.bagsNeeded': 'Bags Needed',
  'createRequest.bag': 'Bag',
  'createRequest.bags': 'Bags',
  'createRequest.hospitalName': 'Hospital Name',
  'createRequest.hospitalAddress': 'Hospital Address',
  'createRequest.searchLocation': 'Search location or enter manually below',
  'createRequest.searchHospital': 'Search hospital name...',
  'createRequest.manualAddressPlaceholder': 'Enter hospital address manually',
  'createRequest.manualAddressHint': 'If search doesn\'t find your hospital, enter the address manually here',
  'createRequest.area': 'Area',
  'createRequest.selectArea': 'Select area',
  'createRequest.notes': 'Additional Notes',
  'createRequest.notesPlaceholder': 'Any extra information... (optional)',
  'createRequest.emergencyRequest': 'Emergency Request',
  'createRequest.emergencyInfo': 'Notify matching donors in this area',
  'createRequest.amberAlert': 'Amber Alert',
  'createRequest.amberAlertInfo': 'Critical emergency! Alert all matching donors regardless of area',
  'createRequest.submitting': 'Submitting...',
  'createRequest.submitRequest': 'Submit Request',

  // Requests page
  'requests.soundOn': 'Sound On',
  'requests.soundOff': 'Sound Off',
  'requests.all': 'All',
  'requests.pendingRequests': 'Pending Requests',
  'requests.acceptedRequests': 'Accepted Requests',
  'requests.noIncoming': 'No incoming requests',
  'requests.noIncomingDesc': 'When someone needs blood matching your blood group, you will see requests here.',
  'requests.noMyRequests': 'No requests yet',
  'requests.noMyRequestsDesc': 'Your blood requests will appear here.',
  'requests.noScheduled': 'No scheduled requests',
  'requests.noScheduledDesc': 'Scheduled blood donation bookings will appear here.',
  'requests.viewProfile': 'View Profile',
  'requests.navigate': 'Navigate',
  'requests.call': 'Call',
  'requests.confirmAccept': 'Confirm Accept',
  'requests.confirmAcceptDesc': 'Are you sure you want to accept this blood donation request?',
  'requests.confirmDecline': 'Decline Request',
  'requests.confirmDeclineDesc': 'Are you sure you want to decline this request? The requester will be notified.',
  'requests.confirmCancel': 'Cancel Request',
  'requests.confirmCancelDesc': 'Are you sure you want to cancel this request? This cannot be undone.',
  'requests.confirmComplete': 'Mark as Complete',
  'requests.confirmCompleteDesc': 'Confirm that this donation has been completed successfully.',
  'requests.scheduledFor': 'Scheduled for',
  'requests.accepted': 'Accepted',
  'requests.declined': 'Declined',
  'requests.acceptSuccess': 'Request accepted! The requester has been notified.',
  'requests.declineSuccess': 'Request declined.',
  'requests.cancelSuccess': 'Request cancelled.',
  'requests.completeSuccess': 'Donation marked as complete. Thank you!',
};

// Bengali translations (Modern, contextual - mixing English naturally)
const bn: Record<string, string> = {
  // Common
  'common.loading': 'Loading হচ্ছে...',
  'common.save': 'Save করুন',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.done': 'Done',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.refresh': 'Refresh',
  'common.close': 'Close',
  'common.yes': 'হ্যাঁ',
  'common.no': 'না',
  'common.or': 'অথবা',
  'common.and': 'এবং',

  // Navigation
  'nav.home': 'Home',
  'nav.requests': 'Requests',
  'nav.profile': 'Profile',
  'nav.history': 'History',
  'nav.settings': 'Settings',

  // Auth
  'auth.login': 'Login',
  'auth.logout': 'Logout',
  'auth.signup': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Password Confirm করুন',
  'auth.forgotPassword': 'Password ভুলে গেছেন?',
  'auth.resetPassword': 'Password Reset',
  'auth.phoneNumber': 'Phone Number',
  'auth.sendOTP': 'OTP পাঠান',
  'auth.verifyOTP': 'OTP Verify',
  'auth.signInWithGoogle': 'Google দিয়ে Login',
  'auth.signInWithPhone': 'Phone দিয়ে Login',
  'auth.noAccount': 'Account নেই?',
  'auth.hasAccount': 'Already account আছে?',
  'auth.logoutConfirm': 'আপনি কি Logout করতে চান?',
  'auth.logoutDescription': 'আবার access করতে Login করতে হবে।',
  'auth.continueWithGoogle': 'Google দিয়ে Continue',
  'auth.signingIn': 'Signing in...',
  'auth.sendingOTP': 'OTP পাঠাচ্ছে...',
  'auth.verifying': 'Verifying...',
  'auth.verifyAndSignIn': 'Verify & Sign In',
  'auth.changeNumber': 'Number Change',
  'auth.enterOTP': 'OTP Enter করুন',
  'auth.otpSentTo': 'যে number-এ 6-digit code পাঠানো হয়েছে',
  'auth.enterBDPhone': 'আপনার Bangladesh phone number দিন',
  'auth.creating': 'Creating...',
  'auth.sending': 'Sending...',
  'auth.createAccount': 'Account Create',
  'auth.sendResetLink': 'Reset Link পাঠান',
  'auth.signIn': 'Sign In',
  'auth.resetEmailInfo': 'আপনার email দিন, আমরা password reset link পাঠাবো।',
  'auth.passwordHint.signup': 'Minimum 6 characters দিন।',
  'auth.passwordHint.signin': 'Sign up করার সময় যে password দিয়েছিলেন।',

  // Profile
  'profile.title': 'Profile',
  'profile.editProfile': 'Profile Edit',
  'profile.fullName': 'Full Name',
  'profile.phoneNumber': 'Phone Number',
  'profile.bloodGroup': 'Blood Group',
  'profile.area': 'Area',
  'profile.email': 'Email',
  'profile.memberSince': 'Member Since',
  'profile.updateSuccess': 'Profile update হয়েছে!',
  'profile.updateError': 'Profile update করতে পারছি না',

  // Donor
  'donor.title': 'Donor Settings',
  'donor.description': 'আপনার blood donation availability manage করুন',
  'donor.registerAsDonor': 'Donor হিসেবে Register',
  'donor.receiveRequests': 'Blood donation requests receive করুন',
  'donor.availableToDonate': 'Donate করতে Ready',
  'donor.toggleAvailability': 'Availability on/off করুন',
  'donor.inCooldown': 'Cooldown Period-এ আছেন',
  'donor.cooldownInfo': 'Cooldown Info',
  'donor.cooldownDays': 'দিন বাকি',
  'donor.cooldownEnds': 'Cooldown শেষ হবে',
  'donor.lastDonation': 'Last Donation',
  'donor.neverDonated': 'এখনো donate করিনি',
  'donor.moreThan3Months': '3 মাসের বেশি আগে',
  'donor.lessThan3Months': '3 মাসের কম আগে',
  'donor.firstDonation': 'এটা আমার first donation হবে',
  'donor.readyToDonate': 'আবার donate করতে ready',
  'donor.willBeInCooldown': 'আপনি cooldown period-এ থাকবেন',
  'donor.daysAgo': 'কত দিন আগে?',
  'donor.immediatelyAvailable': 'আপনি immediately donation-এর জন্য available থাকবেন',
  'donor.registerSuccess': 'আপনি এখন donor হিসেবে registered!',
  'donor.modeDisabled': 'Donor mode off করা হয়েছে',
  'donor.status.available': 'Available',
  'donor.status.unavailable': 'Unavailable',
  'donor.status.cooldown': 'Cooldown',

  // Requests
  'requests.title': 'Blood Requests',
  'requests.incoming': 'Incoming',
  'requests.myRequests': 'My Requests',
  'requests.scheduled': 'Scheduled',
  'requests.createRequest': 'Request Create',
  'requests.patientName': 'Patient Name',
  'requests.hospital': 'Hospital',
  'requests.bagsNeeded': 'Bags Needed',
  'requests.urgency': 'Urgency',
  'requests.notes': 'Notes',
  'requests.contactNumber': 'Contact Number',
  'requests.noRequests': 'কোনো request নেই',
  'requests.accept': 'Accept',
  'requests.decline': 'Decline',
  'requests.cancel': 'Cancel Request',
  'requests.complete': 'Complete',
  'requests.viewHistory': 'History দেখুন',
  'requests.status.pending': 'Pending',
  'requests.status.accepted': 'Accepted',
  'requests.status.declined': 'Declined',
  'requests.status.completed': 'Completed',
  'requests.status.cancelled': 'Cancelled',
  'requests.status.expired': 'Expired',
  'requests.urgency.normal': 'Normal',
  'requests.urgency.urgent': 'Urgent',
  'requests.urgency.critical': 'Critical',

  // History
  'history.title': 'History',
  'history.myDonations': 'My Donations',
  'history.myRequests': 'My Requests',
  'history.totalDonations': 'Total Donations',
  'history.bagsDonated': 'Bags Donated',
  'history.peopleHelped': 'মানুষ Help করেছেন',
  'history.totalRequests': 'Total Requests',
  'history.completed': 'Completed',
  'history.pending': 'Pending',
  'history.noHistory': 'কোনো history নেই',
  'history.filterAll': 'All',
  'history.filterCompleted': 'Completed',
  'history.filterPending': 'Pending',
  'history.filterAccepted': 'Accepted',
  'history.filterDeclined': 'Declined',
  'history.filterCancelled': 'Cancelled',
  'history.filterExpired': 'Expired',

  // Home
  'home.welcome': 'Welcome',
  'home.findDonors': 'Donors খুঁজুন',
  'home.requestBlood': 'Blood Request',
  'home.becomeDonor': 'Donor হন',
  'home.nearbyDonors': 'কাছের Donors',
  'home.recentRequests': 'Recent Requests',
  'home.quickActions': 'Quick Actions',

  // Notifications
  'notifications.title': 'Notifications',
  'notifications.markAllRead': 'সব Read করুন',
  'notifications.noNotifications': 'কোনো notification নেই',
  'notifications.enable': 'Notifications On করুন',
  'notifications.enabled': 'Push notifications চালু আছে',
  'notifications.enableDescription': 'Blood দরকার হলে notification পান',

  // Settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.languageDescription': 'আপনার preferred language select করুন',
  'settings.english': 'English',
  'settings.bangla': 'বাংলা',
  'settings.notifications': 'Notifications',
  'settings.privacy': 'Privacy',
  'settings.about': 'About',
  'settings.help': 'Help & Support',

  // Location
  'location.title': 'Location',
  'location.enable': 'Location On করুন',
  'location.enableDescription': 'কাছের donors খুঁজতে location access দিন',
  'location.sharing': 'Location Sharing',
  'location.sharingActive': 'আপনার location share হচ্ছে',
  'location.allowAccess': 'Location Access দিন',
  'location.skipForNow': 'পরে করবো',

  // Errors
  'error.general': 'কিছু একটা problem হয়েছে',
  'error.network': 'Network error। আবার try করুন।',
  'error.notFound': 'Page পাওয়া যায়নি',
  'error.unauthorized': 'Continue করতে login করুন',

  // Login page specific
  'login.title': 'RoktoLagbe',
  'login.subtitle': 'Bangladesh-এর Emergency blood donation coordination',
  'login.feature1.title': 'Instantly Donors খুঁজুন',
  'login.feature1.description': 'Blood group ও area দিয়ে search করুন',
  'login.feature2.title': 'Emergency Alerts',
  'login.feature2.description': 'Matching donors-দের urgent request পাঠান',
  'login.feature3.title': 'Hospital-এ Navigate করুন',
  'login.feature3.description': 'Patient-এর location-এ directions পান',
  'login.google': 'Google',
  'login.phone': 'Phone',
  'login.email': 'Email',
  'login.tagline': 'প্রতিটা রক্তের ফোঁটা গুনে',

  // Create Request page
  'createRequest.title': 'Blood Request Create',
  'createRequest.formTitle': 'Blood Request Form',
  'createRequest.formDescription': 'Blood donors খুঁজতে details দিন',
  'createRequest.requestFrom': 'Request from',
  'createRequest.fillDetails': 'এই donor-এর কাছে request করতে details দিন',
  'createRequest.requestType': 'Request Type',
  'createRequest.immediate': 'Immediate',
  'createRequest.bookForLater': 'পরে Book করুন',
  'createRequest.bookingInfo': 'Future date-এ blood donation schedule করুন (যেমন surgery, pregnancy)',
  'createRequest.date': 'Date',
  'createRequest.time': 'Time',
  'createRequest.requestForSelf': 'নিজের জন্য Request',
  'createRequest.autoFill': 'আপনার details auto-fill হবে',
  'createRequest.patientName': 'Patient-এর নাম',
  'createRequest.contactPhone': 'Contact Phone',
  'createRequest.bloodGroup': 'Blood Group',
  'createRequest.selectBloodGroup': 'Blood group select করুন',
  'createRequest.bagsNeeded': 'কত Bag দরকার',
  'createRequest.bag': 'Bag',
  'createRequest.bags': 'Bags',
  'createRequest.hospitalName': 'Hospital-এর নাম',
  'createRequest.hospitalAddress': 'Hospital Address',
  'createRequest.searchLocation': 'Location search করুন অথবা নিচে manually লিখুন',
  'createRequest.searchHospital': 'Hospital name search করুন...',
  'createRequest.manualAddressPlaceholder': 'Hospital-এর address manually লিখুন',
  'createRequest.manualAddressHint': 'Search-এ hospital না পেলে, নিচে address manually লিখুন',
  'createRequest.area': 'Area',
  'createRequest.selectArea': 'Area select করুন',
  'createRequest.notes': 'Additional Notes',
  'createRequest.notesPlaceholder': 'যেকোনো extra information... (optional)',
  'createRequest.emergencyRequest': 'Emergency Request',
  'createRequest.emergencyInfo': 'এই area-র matching donors-দের notify করুন',
  'createRequest.amberAlert': 'Amber Alert',
  'createRequest.amberAlertInfo': 'Critical emergency! সব matching donors-কে alert করুন, area যাই হোক',
  'createRequest.submitting': 'Submit হচ্ছে...',
  'createRequest.submitRequest': 'Request Submit করুন',

  // Requests page
  'requests.soundOn': 'Sound On',
  'requests.soundOff': 'Sound Off',
  'requests.pullToRefresh': 'Refresh করতে টানুন',
  'requests.releaseToRefresh': 'Refresh করতে ছেড়ে দিন',
  'requests.refreshing': 'Refreshing...',
  'requests.incomingRequests': 'Incoming Requests',
  'requests.myBookings': 'My Bookings',
  'requests.acceptedBookings': 'Accepted Bookings',
  'requests.noPendingRequests': 'কোনো pending request নেই',
  'requests.noBookings': 'কোনো booking নেই',
  'requests.bags': 'bags',
  'requests.viewOnMap': 'Map-এ দেখুন',
  'requests.call': 'Call',
  'requests.sendReminder': 'Reminder পাঠান',
  'requests.cancelRequest': 'Request Cancel',
  'requests.markComplete': 'Complete',
  'requests.navigate': 'Navigate',
  'requests.chat': 'Chat',
  'requests.liveLocation': 'Live Location',
  'requests.eta': 'ETA',
  'requests.away': 'দূরে',
  'requests.scheduledFor': 'Scheduled for',
  'requests.booking': 'Booking',
};

const translations: Record<Language, Record<string, string>> = { en, bn };

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem(LANGUAGE_KEY) as Language | null;
    if (saved && (saved === 'en' || saved === 'bn')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
